name: Train CVAE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create folders
        run: |
          mkdir -p data model

      - name: Run training
        run: |
          python training_script_fixed.py \
            --data-dir ./data \
            --model-dir ./model \
            --epochs 2 \
            --batch-size 32 \
            --latent_dim 120 \
            --num-classes 10 \
            --num-gpus 0

      - name: Test trained model
        run: python test_model.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: modelo_cvae
          path: model/

      - name: Upload generated sample image
        uses: actions/upload-artifact@v4
        with:
          name: generated-image
          path: sample_generated.png
